import Image from 'next/image'
import Thanks from '../../public/thanks.webp'
import { MainContainer, TextContent } from '@/styles/thankspage.styles'
import { Oxygen } from 'next/font/google'
import Head from 'next/head'

const Vietnam = Oxygen({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
})

export default function ThanksPage() {
  return (
    <>
      <Head>
        <title>Congratulations on your purchase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/whatsapp2.webp" />
      </Head>
      <MainContainer className={Vietnam.className}>
        <Image alt="logo" src={Thanks} quality={100} />{' '}
        <TextContent>
          <h1>Congratulations on your purchase!</h1>
          <p>Access will be sent to your email. Very easy to access!</p>
        </TextContent>
      </MainContainer>
    </>
  )
}
